name: Deploy to SSH Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    if: github.repository == 'OZ-RooT/SpringBoot_RooT_Server'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H -p 2201 "$SSH_HOST" >> ~/.ssh/known_hosts || true

      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new -p 2201 "$SSH_USER@$SSH_HOST" << 'EOF'
            set -e
            cd SpringBoot_RooT_Server/
            git pull origin main
            docker compose build
            docker tag root_server localhost:5000/root_server:latest
            docker push localhost:5000/root_server:latest
            kubectl rollout restart deploy root-springboot
          EOF
